name: Build

on: [push]

env:
  BUILD_TYPE: Release
  HASH_MAP: USE_TSL_ROBIN_MAP

jobs:
  build:
    name: ${{matrix.buildname}}

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-10.15, macos-11.0 ]
        include:
          - os: ubuntu-20.04
            buildname: 'ubuntu-20.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: ubuntu-18.04
            buildname: 'ubuntu-18.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: macos-10.15
            buildname: 'macos-10.15'
            triplet: x64-osx
            compiler: clang_64
          - os: macos-11.0
            buildname: 'macos-11.0'
            triplet: x64-osx
            compiler: clang_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: (MacOS) Install dependencies
        if: runner.os == 'macOS'
        run: brew install boost libomp

      - name: (Linux) Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-serialization-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev zlib1g-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/bin

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/bin
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHASH_MAP=$HASH_MAP

      - name: Build all
        working-directory: ${{runner.workspace}}/bin
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Build tests
        working-directory: ${{runner.workspace}}/bin
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --target test_dna

      - name: Test
        working-directory: ${{runner.workspace}}/bin
        shell: bash
        run: (cd tests; ctest -C $BUILD_TYPE)
